gcs_bucket: multicryptoreal

row_interval_seconds: 1
upload_interval_seconds: 60

# expanded asset list
assets: [BTC, ETH, ADA, SOL, XRP, LINK]

exchanges:
  coinbase:
    enabled: true
    quote: USD
    rate_limit_rps: 8


